<?php

session_start();
include 'config.php';
include 'core/db.php';
include 'core/core.php';
include 'core/ui.php';
include 'core/libreport.php';



define('PAGE_SEC','control');
cr_logic();

ui_sp('Управление');
    $menuitems=array();
    $menuitems[]=(cr_check('control.targetacl'))?'<a class="ctl_lnk" href="createHtml2.php?MODE=DISPLAY" target="blank">Контрольные цифры</a>':'';
    $menuitems[]=(cr_check('control.users'))?'<a class="ctl_lnk" href="users.php">Пользователи</a>':'';
    $menuitems[]=(cr_check('control.groups'))?'<a class="ctl_lnk" href="groups.php">Группы</a>':'';
    $menuitems[]=(cr_check('control.keys'))?'<a class="ctl_lnk" href="keys.php">Ключи</a>':'';
    $menuitems[]=(cr_check('control.submitted'))?'<a class="ctl_lnk" href="submitted.php">Поданные цифры*</a>':'';
    $menuitems[]=(cr_check('control.submissions'))?'<a class="ctl_lnk" href="submissions.php">Подчинение</a>':'';
    $menuitems[]='<hr style="clear:both;" />';
    $menuitems[]=(cr_check('control.dual_modes'))?'<a class="ctl_lnk" href="dual_modes.php">Доп.заявления</a>':'';
    $menuitems[]=(cr_check('control.ct_info_load'))?'<a class="ctl_lnk" href="ct_info_load.php">Данные ЦТ</a>':'';
    $menuitems[]=(cr_check('control.facultys'))?'<a class="ctl_lnk" href="facultys.php">Факультеты</a>':'';
    $menuitems[]=(cr_check('control.time_forms'))?'<a class="ctl_lnk" href="time_forms.php">Формы посещения</a>':'';
    $menuitems[]=(cr_check('control.edu_forms'))?'<a class="ctl_lnk" href="edu_forms.php">Формы обучения</a>':'';
    $menuitems[]=(cr_check('control.targets'))?'<a class="ctl_lnk" href="targets.php">Конкурсы</a>':'';
    $menuitems[]=(cr_check('control.targettypes'))?'<a class="ctl_lnk" href="targettypes.php">Типы конкурса</a>':'';
    $menuitems[]=(cr_check('control.targetcells'))?'<a class="ctl_lnk" href="targetcells.php">Типы целевых</a>':'';
    $menuitems[]='<hr style="clear:both;" />';
    $menuitems[]=(cr_check('control.plancells'))?'<a class="ctl_lnk" href="plancells.php">План целевых<sup>*</sup></a>':'';
    $menuitems[]=(cr_check('control.planform'))?'<a class="ctl_lnk" href="planform.php">План приёма<sup>*</sup></a>':'';
    $menuitems[]=(cr_check('control.targetacl'))?'<a class="ctl_lnk" href="targetacl.php">Допустимый конкурс<sup>!!!</sup> </a>':'';
    $menuitems[]=(cr_check('control.targetacl'))?'<a class="ctl_lnk" href="formacl.php">Допустимый конкурс форм<sup>!!!</sup> </a>':'';
    $menuitems[]='<hr style="clear:both;" />';
    $menuitems[]=(cr_check('control.states'))?'<a class="ctl_lnk" href="states.php">Состояние дела</a>':'';
    $menuitems[]=(cr_check('control.sexs'))?'<a class="ctl_lnk" href="sexs.php">Пол</a>':'';
    $menuitems[]=(cr_check('control.countrys'))?'<a class="ctl_lnk" href="natios.php">Гражданство</a>':'';
    $menuitems[]=(cr_check('control.countrys'))?'<a class="ctl_lnk" href="countrys.php">Страны</a>':'';
    $menuitems[]=(cr_check('control.regions'))?'<a class="ctl_lnk" href="regions.php">Области</a>':'';
    $menuitems[]=(cr_check('control.subdivs'))?'<a class="ctl_lnk" href="subdivs.php">Типы городов</a>':'';
    $menuitems[]=(cr_check('control.institutions'))?'<a class="ctl_lnk" href="institutions.php">Типы УО</a>':'';
    $menuitems[]=(cr_check('control.educations'))?'<a class="ctl_lnk" href="educations.php">Типы Обр</a>':'';
    $menuitems[]=(cr_check('control.certificates'))?'<a class="ctl_lnk" href="certificates.php">Документы Обр</a>':'';
    $menuitems[]=(cr_check('control.languages'))?'<a class="ctl_lnk" href="languages.php">Языки</a>':'';
    $menuitems[]=(cr_check('control.benefits'))?'<a class="ctl_lnk" href="benefits.php">Льготы</a>':'';
    $menuitems[]=(cr_check('control.communitys'))?'<a class="ctl_lnk" href="communitys.php">Организации</a>':'';
    $menuitems[]=(cr_check('control.others'))?'<a class="ctl_lnk" href="others.php">Др Документы</a>':'';
    $menuitems[]=(cr_check('control.experiences'))?'<a class="ctl_lnk" href="experiences.php">Опыт работы</a>':'';
    $menuitems[]=(cr_check('control.militarys'))?'<a class="ctl_lnk" href="militarys.php">Военка</a>':'';
    $menuitems[]=(cr_check('control.trys'))?'<a class="ctl_lnk" href="trys.php">Попытки</a>':'';
    $menuitems[]=(cr_check('control.hostels'))?'<a class="ctl_lnk" href="hostels.php">Общага</a>':'';
    $menuitems[]=(cr_check('control.courses'))?'<a class="ctl_lnk" href="courses.php">Курсы</a>':'';
    $menuitems[]=(cr_check('control.grades'))?'<a class="ctl_lnk" href="grades.php">Награды</a>':'';
    $menuitems[]=(cr_check('control.stalker'))?'<a class="ctl_lnk" href="stalkers.php">ЧАЭС</a>':'';
    $menuitems[]=(cr_check('control.smalltowns'))?'<a class="ctl_lnk" href="smalltowns.php">Малые города</a>':'';
    $menuitems[]=(cr_check('control.nametowns'))?'<a class="ctl_lnk" href="nametowns.php">Города</a>':'';
    $menuitems[]=(cr_check('control.voenmeds'))?'<a class="ctl_lnk" href="voenmeds.php">Абитуриенты ВМ</a>':'';
    $menuitems[]=(cr_check('control.presidents'))?'<a class="ctl_lnk" href="presidents.php">Лауреаты СФ</a>':'';
    $menuitems[]=(cr_check('control.republics'))?'<a class="ctl_lnk" href="republics.php">Олимпиада</a>':'';
    $menuitems[]=(cr_check('control.reasons'))?'<a class="ctl_lnk" href="reasons.php">Причина начала конкурса</a>':'';
    $menuitems[]=(cr_check('control.reasoffs'))?'<a class="ctl_lnk" href="reasoffs.php">Причина окончания конкурса</a>':'';
    $menuitems[]=(cr_check('control.inst_ranks'))?'<a class="ctl_lnk" href="inst_ranks.php">Ранги УО</a>':'';
    $menuitems[]=(cr_check('control.students'))?'<a class="ctl_lnk" href="students.php">Зачислен/Отчислен</a>':'';
    $menuitems[]=(cr_check('control.xclasss'))?'<a class="ctl_lnk" href="xclasss.php">Штрих-класс</a>':'';
    $menuitems[]=(cr_check('control.wouldbes'))?'<a class="ctl_lnk" href="wouldbes.php">Потенциальные личности</a>':'';
    $menuitems[]=(cr_check('control.lang_levels'))?'<a class="ctl_lnk" href="lang_levels.php">Уровень иностранного</a>':'';
    $menuitems[]=(cr_check('control.inventory_docs'))?'<a class="ctl_lnk" href="inventory_docs.php">Документы описи</a>':'';
    $menuitems[]=(cr_check('control.monids'))?'<a class="ctl_lnk" href="monids.php">ID мониторинга</a>':'';
    $menuitems[]=(cr_check('control.calls'))?'<a class="ctl_lnk" href="calls.php">Звонки</a>':'';
    $menuitems[]=(cr_check('control.calls'))?'<a class="ctl_lnk" href="faxs.php">Факсы</a>':'';
    $menuitems[]=(cr_check('control.calls'))?'<a class="ctl_lnk" href="mails.php">Письма</a>':'';

    $menuitems[]=(cr_check('control.city_rangs'))?'<a class="ctl_lnk" href="city_rangs.php">Ранги населённых пунктов</a>':'';
    $menuitems[]=(cr_check('control.cts'))?'<a class="ctl_lnk" href="cts.php">Сертификат и не только</a>':'';
    $menuitems[]=(cr_check('control.invalid'))?'<a class="ctl_lnk" href="invalids.php">Инвалидность</a>':'';
    $menuitems[]=(cr_check('control.invalid'))?'<a class="ctl_lnk" href="iracl.php">Ранг - Тип УО</a>':'';
    
    $menuitems[]='<hr style="clear:both;" />';
    $menuitems[]=(cr_check('control.months'))?'<a class="ctl_lnk" href="months.php">Месяцы</a>':'';
    $menuitems[]=(cr_check('control.tasks'))?'<a class="ctl_lnk" href="tasks.php">Таски</a>':'';
    $menuitems[]=(cr_check('control.querys'))?'<a class="ctl_lnk" href="querys.php">Запросы</a>':'';
    $menuitems[]=(cr_check('control.chains'))?'<a class="ctl_lnk" href="chains.php">Цепочки</a>':'';
    $menuitems[]=(cr_check('control.tags'))?'<a class="ctl_lnk" href="tags.php">Тэги</a>':'';
    $menuitems[]=(cr_check('control.cuts'))?'<a class="ctl_lnk" href="cuts.php">Срезы</a>':'';
    $menuitems[]=(cr_check('control.helps'))?'<a class="ctl_lnk" href="helps.php">Помощь</a>':'';
    $menuitems[]=(cr_check('control.queues'))?'<a class="ctl_lnk" href="queues.php">Очереди</a>':'';
    $menuitems[]=(cr_check('control.phones_bsmus'))?'<a class="ctl_lnk" href="phones_bsmus.php">Телефоны БГМУ</a>':'';
    $menuitems[]=(cr_check('control.phones_uzos'))?'<a class="ctl_lnk" href="phones_uzos.php">Телефоны УЗО</a>':'';
    $menuitems[]=(cr_check('control.phone_codes'))?'<a class="ctl_lnk" href="phone_codess.php">Коды городов</a>':'';
    $menuitems[]=(cr_check('control.vized_cells'))?'<a class="ctl_lnk" href="vized_cells.php">Заключённые договора</a>':'';
    $menuitems[]=(cr_check('control.po_bsmus'))?'<a class="ctl_lnk" href="po_bsmus.php">ПО БГМУ (з)</a>':'';
    $menuitems[]=(cr_check('control.klik'))?'<a class="ctl_lnk" href="kliks.php">Клик</a>':'';
    $menuitems[]='<hr style="clear:both;" />';
$menuitems[]=(cr_check('control.cron_config'))?'<a class="ctl_lnk" href="cron_config.php">Настройка Cron</a>':'';
    $menuitems[]=(cr_check('control.savefields'))?'<a class="ctl_lnk" href="savefields.php">Сохранённые поля</a>':'';
    $menuitems[]=(cr_check('control.manualfixation'))?'<a class="ctl_lnk" href="manualfixation.php">Ручная фиксация</a>':'';
    $menuitems[]=(cr_check('control.cron_config_sa'))?'<a class="ctl_lnk" href="cron_config_sa.php">Ручная выгрузка</a>':'';
    $menuitems[]=(cr_check('person.defaults'))?'<a class="ctl_lnk" href="defaults.php">Дефолт</a>':'';
    $menuitems[]=(cr_check('person.settings'))?'<a class="ctl_lnk" href="settings.php">Настройки</a>':'';
    $menuitems[]=(cr_check('person.macro_dict'))?'<a class="ctl_lnk" href="macro_dict.php">Макрос Словаря</a>':'';
    $menuitems[]=(cr_check('person.field_macros'))?'<a class="ctl_lnk" href="field_macros.php">МакросПоля</a>':'';
    $menuitems[]=(cr_check('person.dumper'))?'<a class="ctl_lnk" href="dumper.php">Дамп</a>':'';
    $menuitems[]=(cr_check('control.devnull'))?'<a class="ctl_lnk" href="devnull.php">Отчистить всё</a>':'';
    $menuitems[]=(cr_check('control.devzero'))?'<a class="ctl_lnk" href="devzero.php">Занулить</a>':'';
    $menuitems[]='<hr style="clear:both;" />';
    print implode('',  array_filter($menuitems,'strlen'));
ui_ep();